# Generated by Django 4.0.4 on 2022-05-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_pass', models.CharField(max_length=10)),
                ('admin_name', models.CharField(max_length=10)),
                ('admin_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminPay',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin_pay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=10000)),
                ('time', models.DateField()),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleM',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_money', models.IntegerField()),
            ],
            options={
                'db_table': 'article_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleResult',
            fields=[
                ('article_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'article_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author_pass', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=10)),
                ('author_phone', models.IntegerField()),
                ('author_email', models.CharField(max_length=20)),
                ('author_adress', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorM',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_money', models.IntegerField()),
            ],
            options={
                'db_table': 'author_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RA',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('result', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'r_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reviewer_pass', models.CharField(max_length=20)),
                ('reviewer_name', models.CharField(max_length=10)),
                ('reviewer_phone', models.IntegerField()),
            ],
            options={
                'db_table': 'reviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerAdmin',
            fields=[
                ('reviewer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reviewer_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerM',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reviewer_money', models.IntegerField()),
                ('get', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'reviewer_m',
                'managed': False,
            },
        ),
    ]
